const tours=[
{id:'whale',name:'Whale Watching Sailboat',cat:'Sea',tag:'OCEAN FAVOURITE',image:'whale-sailing.webp',alt:'Illustrative sailboat and pilot whale near Tenerife',description:'Set sail to watch Tenerife’s resident marine life and enjoy time on the Atlantic. Ask us which boat and departure best suit your plans.',meta:['About 3 hours','Sailing experience']},
{id:'charter',name:'Private Sailing Charter',cat:'Private',tag:'YOUR OWN BOAT',image:'whale-sailing.webp',alt:'Illustrative yacht off Tenerife',description:'A private sailing trip for your group, with a route and duration tailored to the occasion. Share your plans and we’ll confirm the options.',meta:['Custom duration','Private group']},
{id:'buggy-morning',name:'Teide Buggy Morning',cat:'Land',tag:'VOLCANIC ADVENTURE',image:'teide-buggy.webp',alt:'Illustrative buggy tour in volcanic Tenerife landscape',description:'Head out through Tenerife’s volcanic landscape on a guided buggy excursion, with mountain views and plenty of fresh air.',meta:['About 3 hours','Morning departure']},
{id:'buggy-sunset',name:'Teide Buggy Sunset',cat:'Land',tag:'GOLDEN HOUR',image:'teide-buggy.webp',alt:'Illustrative Teide buggy tour',description:'Explore volcanic scenery as the afternoon light changes. An unforgettable way to see the island at golden hour.',meta:['About 3 hours','Sunset tour']},
{id:'masca',name:'Masca, Los Gigantes & Pools',cat:'Land',tag:'ISLAND DISCOVERY',image:'masca.webp',alt:'Illustrative Masca valley scenery',description:'Discover Masca village, take in the cliffs of Los Gigantes and ask about a stop at a natural volcanic pool.',meta:['About 5 hours','Small-group van']},
{id:'jetski',name:'Jet Ski Adventure',cat:'Sea',tag:'ADRENALINE',image:'jet-ski-real.jpeg',alt:'Jet ski excursion on the Atlantic',description:'Take to the Atlantic by jet ski and enjoy Tenerife’s coast from the water. Tell us your preferred date and we’ll check the available rides.',meta:['Atlantic coast','Guided activity']}
];
const grid=document.getElementById('tour-grid'),dialog=document.getElementById('booking');let selected=tours[0];
function render(filter='All'){grid.innerHTML=tours.filter(t=>filter==='All'||t.cat===filter).map(t=>`<article class="tour-card"><div class="tour-photo"><img loading="lazy" src="https://oryx-tenerife.emileros1971.chatgpt.site/media/${t.image}" alt="${t.alt}"><span class="tour-tag">${t.tag}</span></div><div class="tour-body"><h3>${t.name}</h3><p>${t.description}</p><div class="tour-meta">${t.meta.map(m=>`<span>◈ ${m}</span>`).join('')}</div><div class="tour-bottom"><div><strong>€99</strong><small>guide price*</small></div><button data-book="${t.id}">Book now</button></div></div></article>`).join('')}
render();document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render(b.dataset.filter)}));document.querySelectorAll('[data-filter-link]').forEach(a=>a.addEventListener('click',()=>document.querySelector(`[data-filter="${a.dataset.filterLink}"]`).click()));
document.addEventListener('click',e=>{const b=e.target.closest('[data-book]');if(!b)return;selected=tours.find(t=>t.id===b.dataset.book);document.getElementById('booking-title').textContent=selected.name;dialog.showModal()});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});document.getElementById('date').min=new Date().toISOString().slice(0,10);
document.getElementById('reserve').addEventListener('click',()=>{const date=document.getElementById('date'),adults=document.getElementById('adults'),children=document.getElementById('children'),pickup=document.getElementById('pickup');if(!date.value){date.reportValidity();return}const message=`Hello Oryx Tourist Services! I’m interested in ${selected.name}. Preferred date: ${date.value}. Adults: ${adults.value || 1}. Children: ${children.value || 0}.${pickup.value.trim()?` Pickup area/hotel: ${pickup.value.trim()}.`:''} Please confirm availability, inclusions and final price. (Website guide price: €99.)`;window.open(`https://wa.me/34604259695?text=${encodeURIComponent(message)}`,'_blank','noopener')});
const menu=document.getElementById('menu'),nav=document.getElementById('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const gameStage=document.getElementById('game-stage'),gameStart=document.getElementById('start-game');let gameTimer,spawnTimer,score=0,time=20;gameStart.addEventListener('click',()=>{clearInterval(gameTimer);clearInterval(spawnTimer);score=0;time=20;document.getElementById('game-score').textContent='0';document.getElementById('game-time').textContent='20';gameStage.innerHTML='';gameStart.disabled=true;const spawn=()=>{const ticket=document.createElement('button');ticket.className='ticket';ticket.type='button';ticket.textContent='🎟️';ticket.setAttribute('aria-label','Catch ticket');ticket.style.left=Math.max(3,Math.random()*78)+'%';ticket.style.top=Math.max(4,Math.random()*70)+'%';ticket.addEventListener('click',()=>{score++;document.getElementById('game-score').textContent=String(score);ticket.remove()});gameStage.append(ticket);setTimeout(()=>ticket.remove(),1100)};spawn();spawnTimer=setInterval(spawn,900);gameTimer=setInterval(()=>{time--;document.getElementById('game-time').textContent=String(time);if(time<=0){clearInterval(gameTimer);clearInterval(spawnTimer);gameStage.innerHTML=`<p>Nice catch! You collected ${score} tickets.</p>`;gameStart.disabled=false;gameStart.textContent='Play again'}},1000)});
